# Generated by Django 5.2.dev20240907175003 on 2024-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riboApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adapter", models.CharField(max_length=500)),
                ("mouseGenome", models.BooleanField()),
                ("humanGenome", models.BooleanField()),
                ("sampleFile", models.FileField(upload_to="")),
            ],
        ),
    ]
