# Generated by Django 5.2.dev20240907175003 on 2024-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riboApp", "0002_processinginput"),
    ]

    operations = [
        migrations.AddField(
            model_name="processinginput",
            name="experimentName",
            field=models.CharField(default="unknown", max_length=200),
            preserve_default=False,
        ),
    ]
