# Generated by Django 5.1.2 on 2025-02-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riboApp", "0004_alter_processinginput_samplefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParquetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene_name", models.CharField(max_length=255)),
                ("data", models.JSONField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedParquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="parquetFiles/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
