# Generated by Django 5.1.2 on 2025-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riboApp", "0005_parquetdata_uploadedparquet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parquetdata",
            name="data",
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="additional_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="end_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="read_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="read_id",
            field=models.CharField(default="NA", max_length=255),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="read_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="region",
            field=models.CharField(default="NA", max_length=50),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="source_file",
            field=models.CharField(default="NA", max_length=50),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="start_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="strand",
            field=models.CharField(default="NA", max_length=1),
        ),
        migrations.AddField(
            model_name="parquetdata",
            name="transcript_id",
            field=models.CharField(db_index=True, default="NA", max_length=255),
        ),
        migrations.AlterField(
            model_name="parquetdata",
            name="gene_name",
            field=models.CharField(db_index=True, default="NA", max_length=255),
        ),
    ]
