# Generated by Django 5.1.2 on 2025-02-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "riboApp",
            "0006_remove_parquetdata_data_parquetdata_additional_data_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectedGene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene_name", models.CharField(max_length=255, unique=True)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
