# Generated by Django 5.1.2 on 2025-08-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riboApp", "0007_selectedgene"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedMrnaParquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="mrnaFiles/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
