# Generated by Django 5.1.2 on 2025-09-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riboApp", "0008_uploadedmrnaparquet"),
    ]

    operations = [
        migrations.AddField(
            model_name="processinginput",
            name="useBarcode",
            field=models.BooleanField(default=False),
        ),
    ]
